create table public.cover_letters (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, resume_id uuid references public.resumes(id) on delete set null, job_description_id uuid references public.job_descriptions(id) on delete set null, title text not null default 'Untitled cover letter', content jsonb not null default '{}'::jsonb, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.resignation_letters (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, title text not null default 'Untitled resignation letter', content jsonb not null default '{}'::jsonb, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.interview_sessions (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, resume_id uuid references public.resumes(id) on delete set null, job_description_id uuid references public.job_descriptions(id) on delete set null, mode text not null, status text not null default 'draft', summary jsonb not null default '{}'::jsonb, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.interview_questions (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, session_id uuid not null references public.interview_sessions(id) on delete cascade, position integer not null check (position >= 0), question text not null, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique(session_id, position));
create table public.interview_answers (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, question_id uuid not null references public.interview_questions(id) on delete cascade, answer_text text, feedback jsonb not null default '{}'::jsonb, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.job_bookmarks (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, job_description_id uuid references public.job_descriptions(id) on delete set null, source_url text, title text not null, company text, notes text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.job_applications (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, job_bookmark_id uuid references public.job_bookmarks(id) on delete set null, resume_id uuid references public.resumes(id) on delete set null, cover_letter_id uuid references public.cover_letters(id) on delete set null, status public.job_status not null default 'interested', applied_at timestamptz, interview_at timestamptz, compensation text, contact jsonb not null default '{}'::jsonb, notes text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.teams (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, name text not null check (char_length(name) between 1 and 120), created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.team_members (id uuid primary key default gen_random_uuid(), team_id uuid not null references public.teams(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role public.team_role not null default 'member', created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique(team_id, user_id));
create table public.team_invitations (id uuid primary key default gen_random_uuid(), team_id uuid not null references public.teams(id) on delete cascade, invited_by uuid not null default auth.uid() references auth.users(id) on delete cascade, email_hash text not null, role public.team_role not null default 'member', token_hash text not null unique, expires_at timestamptz not null, accepted_at timestamptz, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.review_requests (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, resume_id uuid not null references public.resumes(id) on delete cascade, team_id uuid references public.teams(id) on delete set null, reviewer_id uuid references auth.users(id) on delete set null, status text not null default 'requested', created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.review_comments (id uuid primary key default gen_random_uuid(), review_request_id uuid not null references public.review_requests(id) on delete cascade, author_id uuid not null default auth.uid() references auth.users(id) on delete cascade, section_id uuid references public.resume_sections(id) on delete set null, body text not null, resolved_at timestamptz, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);
create table public.audit_events (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, team_id uuid references public.teams(id) on delete cascade, event_type text not null, target_type text, target_id uuid, metadata jsonb not null default '{}'::jsonb, correlation_id uuid, created_at timestamptz not null default timezone('utc', now()));
create table public.export_history (id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, resume_id uuid references public.resumes(id) on delete set null, format text not null, status text not null, filename text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), deleted_at timestamptz);

do $$ declare t text; begin foreach t in array array['cover_letters','resignation_letters','interview_sessions','interview_questions','interview_answers','job_bookmarks','job_applications','teams','team_members','team_invitations','review_requests','review_comments','export_history'] loop execute format('create trigger %I_updated before update on public.%I for each row execute function public.set_updated_at()', t, t); end loop; end $$;

create index cover_letters_owner_idx on public.cover_letters(owner_id, updated_at desc); create index resignation_letters_owner_idx on public.resignation_letters(owner_id, updated_at desc); create index interview_sessions_owner_idx on public.interview_sessions(owner_id, updated_at desc); create index interview_questions_owner_idx on public.interview_questions(owner_id, session_id); create index interview_answers_owner_idx on public.interview_answers(owner_id, question_id); create index job_bookmarks_owner_idx on public.job_bookmarks(owner_id, updated_at desc); create index job_applications_owner_idx on public.job_applications(owner_id, updated_at desc); create index teams_owner_idx on public.teams(owner_id); create index team_members_user_idx on public.team_members(user_id); create index team_invitations_team_idx on public.team_invitations(team_id); create index review_requests_owner_idx on public.review_requests(owner_id); create index review_comments_author_idx on public.review_comments(author_id); create index audit_events_owner_idx on public.audit_events(owner_id, created_at desc); create index export_history_owner_idx on public.export_history(owner_id, created_at desc);
